import SwiftUI
import SwiftData
import GlucoseCore
import BolusCalculator

/// Review-and-log step for a computed `BolusSuggestion`. The units field is
/// always editable and pre-filled (never auto-submitted) so the person can
/// log what they actually took, which may differ from the suggestion.
struct BolusReviewSheet: View {
    let suggestion: BolusSuggestion
    let carbsGrams: Double
    /// Generated by the caller before presenting this sheet; stored on the
    /// logged `InsulinDose.linkedSuggestionID` purely as an audit trail.
    let suggestionID: UUID

    @Environment(\.modelContext) private var modelContext
    @Environment(\.dismiss) private var dismiss

    @State private var unitsText: String
    // The carb-grams field on `BolusSuggestionView` is only an input to the
    // calculation, not itself a saved `CarbEntry` -- if the person hasn't
    // logged this meal anywhere else, this is the natural point to do so
    // alongside the dose. Defaulting to on (with an explicit toggle so the
    // choice stays visible and reversible) covers the common case without
    // silently double-logging for anyone who already logged the meal via
    // `CarbEntryForm` separately.
    @State private var alsoLogCarbs = true

    init(suggestion: BolusSuggestion, carbsGrams: Double, suggestionID: UUID) {
        self.suggestion = suggestion
        self.carbsGrams = carbsGrams
        self.suggestionID = suggestionID
        _unitsText = State(initialValue: Self.formattedUnits(suggestion.suggestedUnits))
    }

    private var enteredUnits: Double? { Double(unitsText) }

    private var canLog: Bool {
        guard let enteredUnits else { return false }
        return enteredUnits > 0
    }

    var body: some View {
        NavigationStack {
            Form {
                Section("Suggestion Breakdown") {
                    breakdownRow("Carb component", suggestion.carbComponentUnits)
                    breakdownRow("Correction component", suggestion.correctionComponentUnits)
                    breakdownRow("Insulin on board (subtracted)", -suggestion.insulinOnBoardUnits)
                    HStack {
                        Text("Suggested")
                            .font(.headline)
                        Spacer()
                        Text("\(formattedUnits(suggestion.suggestedUnits)) u")
                            .font(.headline)
                    }
                }

                Section("Used Profile") {
                    Text("\(suggestion.usedProfile.blockName) \u{00B7} \(suggestion.usedProfile.dataPointCount) meals \u{00B7} \(confidenceLabel(suggestion.usedProfile.confidence)) confidence")
                        .font(.subheadline)
                        .foregroundStyle(.secondary)
                }

                if !suggestion.warnings.isEmpty {
                    Section("Warnings") {
                        ForEach(Array(suggestion.warnings.enumerated()), id: \.offset) { _, warning in
                            Label(warningText(warning), systemImage: "exclamationmark.triangle.fill")
                                .foregroundStyle(.orange)
                        }
                    }
                }

                Section("What did you actually take?") {
                    HStack {
                        TextField("Units", text: $unitsText)
                            .keyboardType(.decimalPad)
                        Text("u")
                            .foregroundStyle(.secondary)
                    }
                    Text("Edit this if you took a different dose than suggested.")
                        .font(.caption)
                        .foregroundStyle(.secondary)
                }

                if carbsGrams > 0 {
                    Section {
                        Toggle("Also log \(Int(carbsGrams.rounded()))g carbs eaten", isOn: $alsoLogCarbs)
                    } footer: {
                        Text("Turn this off if you already logged this meal separately.")
                    }
                }
            }
            .navigationTitle("Review & Log")
            .navigationBarTitleDisplayMode(.inline)
            .toolbar {
                ToolbarItem(placement: .cancellationAction) {
                    Button("Cancel") { dismiss() }
                }
                ToolbarItem(placement: .confirmationAction) {
                    Button("Log", action: logDose)
                        .disabled(!canLog)
                }
            }
        }
    }

    private func breakdownRow(_ label: String, _ value: Double) -> some View {
        HStack {
            Text(label)
            Spacer()
            Text("\(value >= 0 ? "" : "-")\(formattedUnits(abs(value))) u")
                .foregroundStyle(.secondary)
        }
    }

    private func confidenceLabel(_ confidence: ConfidenceLevel) -> String {
        switch confidence {
        case .insufficientData: return "insufficient data"
        case .low: return "low"
        case .medium: return "medium"
        case .high: return "high"
        }
    }

    private func warningText(_ warning: BolusWarning) -> String {
        switch warning {
        case .exceedsMaxDose(let clampedFrom):
            return "Raw calculation was \(formattedUnits(clampedFrom))u, capped to your configured max dose."
        case .unusuallyHighVersusHistory(let recentAverage):
            return "This is unusually high vs. your recent average of \(formattedUnits(recentAverage))u."
        case .lowConfidenceProfile(let confidence):
            return "This time block's ratios are \(confidenceLabel(confidence)) confidence -- double check before dosing."
        }
    }

    private func logDose() {
        guard let enteredUnits else { return }

        var linkedCarbEntryID: UUID?
        if alsoLogCarbs, carbsGrams > 0 {
            let carbEntry = CarbEntry(
                timestamp: Date(),
                grams: carbsGrams,
                source: .manualInApp
            )
            modelContext.insert(carbEntry)
            linkedCarbEntryID = carbEntry.id
        }

        let dose = InsulinDose(
            timestamp: Date(),
            units: enteredUnits,
            reason: .bolus,
            linkedCarbEntryID: linkedCarbEntryID,
            linkedSuggestionID: suggestionID,
            source: .manualInApp
        )
        modelContext.insert(dose)
        try? modelContext.save()
        dismiss()
    }

    // Static (not an instance method) so `init` can call it before `self` is
    // fully set up; static members are still visible unqualified from
    // instance method bodies elsewhere in this type.
    private static func formattedUnits(_ value: Double) -> String {
        String(format: "%.2f", value)
    }
}
